### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by mrjulien44** [h4wkmoon/xbmc-domoticz#11]
Hi,

please find below the error i get in debug mode. the popup windows is empty (maybe the fact that widget option cause error is due to this one)

23:45:23.034 T:1220539136   DEBUG: [XBMC Domoticz] - CustomImage :103
23:45:23.034 T:1911697408   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
23:45:23.038 T:1220539136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.domoticz/default.py", line 493, in onInit
                                                self.populateFromDomo()
                                              File "/home/pi/.kodi/addons/script.domoticz/default.py", line 540, in populateFromDomo
                                                results=transformDomoticz(getData())                    # Ask domoticz for data
                                              File "/home/pi/.kodi/addons/script.domoticz/default.py", line 206, in transformDomoticz
                                                icon=__customimages__[myitem[u'TypeImg']][item[u'CustomImage']]+"-"+myitem[u'Status'].lower()+".png"
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by h4wkmoon** [comment]
Hi, 
I moved from Domoticz to Jeedom a few months ago.
This plugin is no longer maintained. 

Feel free to fork, and make it your own.
Sorry.
